# Generated by Django 4.0.1 on 2022-02-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='id',
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
