# Generated by Django 4.0.1 on 2022-03-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_remove_hotel_destination_remove_hotel_salesman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='username',
        ),
    ]
